steps:
  - id: 'prepare-secret'
    name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['-']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --project=${_PROJECT_ID} --secret=${_ENV}-${_SECRET_NAME} --format='get(payload.data)' | tr '_-' '/+' | base64 -d > ${_DECRYPTED_ENV_FILE_LOCATION}

  - id: prepare-build
    name: gcr.io/azoom-x/jq
    waitFor: ['prepare-secret']
    entrypoint: /bin/sh
    args:
      - -c
      - jq '{ name, dependencies, devDependencies }' < package.json > package.deps.json

  - id: 'build-app-image'
    name: 'gcr.io/kaniko-project/executor:latest'
    waitFor: ['prepare-build']
    args:
      - --dockerfile=${_APP_DOCKER_FILE}
      - --destination=gcr.io/${_PROJECT_ID}/${_CLOUD_RUN_SERVICE_NAME}:latest
      - --destination=gcr.io/${_PROJECT_ID}/${_CLOUD_RUN_SERVICE_NAME}:$TAG_NAME
      - --cache=true
      - --cache-ttl=336h

  - id: 'deploy-app'
    name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['build-app-image']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy ${_CLOUD_RUN_SERVICE_NAME} \
          --image gcr.io/$_PROJECT_ID/${_CLOUD_RUN_SERVICE_NAME}:latest \
          --allow-unauthenticated \
          --region asia-northeast1 \
          --platform managed \

substitutions:
  _ENV: staging
  _SECRET_NAME: abo
  _PROJECT_ID: azoom-n-d-phong
  _DECRYPTED_ENV_FILE_LOCATION: ./.env
  _APP_DOCKER_FILE: ./cicd/release/Dockerfile
  _CLOUD_RUN_SERVICE_NAME: staging-abo
timeout: 900s
